name: gh
on:
  push:
    branches:
      - master
  schedule:
    - cron:  '*/30 * * * *'
jobs:
  publish:
    runs-on: ubuntu-18.04
    name: update gh pages
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "master"
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run scripts
        run: |
          python scripts/ghpage.py
      - name: setup git
        run: |
          git config --local user.email "${{ secrets.EMAIL }}"
          git config --local user.name "refraction-ray"
          git add .
          git commit -m "routine update"
      - name: push to gh branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "gh-pages"
          force: true